#ifndef _GMAE_ANIMATION_TYPE_H_
#define _GMAE_ANIMATION_TYPE_H_

#include <unordered_map>
#include <string>

// 1. 定义动画枚举类型（保持原枚举）
enum ANIMATION_CHARACTER {
	ANIMATION_IDLE = 1, // 闲置动画状态
	ANIMATION_RUN, // 奔跑动画状态
	ANIMATION_SQUAT_1, // 下蹲动画状态 1
	ANIMATION_SQUAT_2, // 下蹲动画状态 2
	ANIMATION_JUMP, // 跳跃动画状态

	ANIMATION_ATTACK_1, // 普通攻击动画状态 1
	ANIMATION_ATTACK_2, // 普通攻击动画状态 2
	ANIMATION_THROW_ITEM, // 投掷物品动画状态

	ANIMATION_JUMP_ATTACK_1, // 跳跃时攻击动画状态 1
	ANIMATION_JUMP_ATTACK_2, // 跳跃时攻击动画状态 2
	ANIMATION_JUMP_THROW_ITEM, // 跳跃时投掷物品动画状态

	ANIMATION_SQUATTING_ATTACK_1, // 下蹲时攻击动画状态 1
	ANIMATION_SQUATTING_ATTACK_2, // 下蹲时攻击动画状态 2
	ANIMATION_SQUATTING_THROW_ITEM, // 下蹲时投掷物品动画状态

	ANIMATION_HANGING, // 悬挂动画状态
	ANIMATION_HANGING_MOVE, // 悬挂移动动画状态
	ANIMATION_HANGING_ATTACK_1, // 悬挂时攻击动画状态 1
	ANIMATION_HANGING_ATTACK_2, // 悬挂时攻击动画状态 2
	ANIMATION_HANGING_THROW_ITEM, // 悬挂时投掷物品动画状态

	ANIMATION_HANGING_ROLL_UP, // 悬挂向上翻滚动画状态
	ANIMATION_HANGING_ROLL_DOWN, // 悬挂向下翻滚动画状态
	ANIMATION_SPECIAL_ATTACK, // 特殊攻击动画状态    
};


// 2. 定义枚举到字符串的映射表（用于将枚举值转为可读字符串）
const std::unordered_map<ANIMATION_CHARACTER, std::string> animationEnumToString = {
  {ANIMATION_IDLE, "ANIMATION_IDLE"},
  {ANIMATION_RUN, "ANIMATION_RUN"},
  {ANIMATION_SQUAT_1, "ANIMATION_SQUAT_1"},
  {ANIMATION_SQUAT_2, "ANIMATION_SQUAT_2"},
  {ANIMATION_JUMP, "ANIMATION_JUMP"},

  {ANIMATION_ATTACK_1, "ANIMATION_ATTACK_1"},
  {ANIMATION_ATTACK_2, "ANIMATION_ATTACK_2"},
  {ANIMATION_THROW_ITEM, "ANIMATION_THROW_ITEM"},

  {ANIMATION_JUMP_ATTACK_1, "ANIMATION_JUMP_ATTACK_1"},
  {ANIMATION_JUMP_ATTACK_2, "ANIMATION_JUMP_ATTACK_2"},
  {ANIMATION_JUMP_THROW_ITEM, "ANIMATION_JUMP_THROW_ITEM"},

  {ANIMATION_SQUATTING_ATTACK_1, "ANIMATION_SQUATTING_ATTACK_1"},
  {ANIMATION_SQUATTING_ATTACK_2, "ANIMATION_SQUATTING_ATTACK_2"},
  {ANIMATION_SQUATTING_THROW_ITEM, "ANIMATION_SQUATTING_THROW_ITEM"},

  {ANIMATION_HANGING, "ANIMATION_HANGING"},
  {ANIMATION_HANGING_MOVE, "ANIMATION_HANGING_MOVE"},
  {ANIMATION_HANGING_ATTACK_1, "ANIMATION_HANGING_ATTACK_1"},
  {ANIMATION_HANGING_ATTACK_2, "ANIMATION_HANGING_ATTACK_2"},
  {ANIMATION_HANGING_THROW_ITEM, "ANIMATION_HANGING_THROW_ITEM"},

  {ANIMATION_HANGING_ROLL_UP, "ANIMATION_HANGING_ROLL_UP"},
  {ANIMATION_HANGING_ROLL_DOWN, "ANIMATION_HANGING_ROLL_DOWN"},
  {ANIMATION_SPECIAL_ATTACK, "ANIMATION_SPECIAL_ATTACK"},
};

// 3. 定义字符串到枚举的映射表（用于从配置/日志中解析枚举值）
const std::unordered_map<std::string, ANIMATION_CHARACTER> animationStringToEnum = {
  {"ANIMATION_IDLE", ANIMATION_IDLE},
  {"ANIMATION_RUN", ANIMATION_RUN},
  {"ANIMATION_SQUAT_1", ANIMATION_SQUAT_1},
  {"ANIMATION_SQUAT_2", ANIMATION_SQUAT_2},
  {"ANIMATION_JUMP", ANIMATION_JUMP},

  {"ANIMATION_ATTACK_1", ANIMATION_ATTACK_1},
  {"ANIMATION_ATTACK_2", ANIMATION_ATTACK_2},
  {"ANIMATION_THROW_ITEM", ANIMATION_THROW_ITEM},

  {"ANIMATION_JUMP_ATTACK_1", ANIMATION_JUMP_ATTACK_1},
  {"ANIMATION_JUMP_ATTACK_2", ANIMATION_JUMP_ATTACK_2},
  {"ANIMATION_JUMP_THROW_ITEM", ANIMATION_JUMP_THROW_ITEM},

  {"ANIMATION_SQUATTING_ATTACK_1", ANIMATION_SQUATTING_ATTACK_1},
  {"ANIMATION_SQUATTING_ATTACK_2", ANIMATION_SQUATTING_ATTACK_2},
  {"ANIMATION_SQUATTING_THROW_ITEM", ANIMATION_SQUATTING_THROW_ITEM},

  {"ANIMATION_HANGING", ANIMATION_HANGING},
  {"ANIMATION_HANGING_MOVE", ANIMATION_HANGING_MOVE},
  {"ANIMATION_HANGING_ATTACK_1", ANIMATION_HANGING_ATTACK_1},
  {"ANIMATION_HANGING_ATTACK_2", ANIMATION_HANGING_ATTACK_2},
  {"ANIMATION_HANGING_THROW_ITEM", ANIMATION_HANGING_THROW_ITEM},

  {"ANIMATION_HANGING_ROLL_UP", ANIMATION_HANGING_ROLL_UP},
  {"ANIMATION_HANGING_ROLL_DOWN", ANIMATION_HANGING_ROLL_DOWN},
  {"ANIMATION_SPECIAL_ATTACK", ANIMATION_SPECIAL_ATTACK},
};

// 4. 辅助函数：将枚举转为字符串（带默认值，避免无效枚举）
static std::string animationEnumToStr(ANIMATION_CHARACTER anim) {
	auto it = animationEnumToString.find(anim);
	if (it != animationEnumToString.end()) {
		return it->second; // 找到对应字符串
	}
	return "UNKNOWN_ANIMATION"; // 无效枚举时返回默认值
}

// 5. 辅助函数：将字符串转为枚举（带默认值）
static ANIMATION_CHARACTER animationStrToEnum(const std::string& str) {
	auto it = animationStringToEnum.find(str);
	if (it != animationStringToEnum.end()) {
		return it->second; // 找到对应枚举
	}
	return ANIMATION_IDLE; // 无效字符串时返回默认状态（如闲置）
}

#endif